/// Flutter icons SelloriaIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SelloriaIcon
///      fonts:
///       - asset: fonts/SelloriaIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SelloriaIcon {
  SelloriaIcon._();

  static const _kFontFam = 'SelloriaIcon';

  static const IconData avatar_1 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData avatar = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData back = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData cancel = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData chat_1 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData chat_2 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData copy = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData dislike = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData download_1 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData envelope = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData folder = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData garbage = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData glasses = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData hand = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData headphones = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData house = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData like = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData link = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData magnifying_glass = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData money_bag = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData monitor = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData next = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData padlock = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData paper_plane = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData phone_call = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData photo_camera = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData picture = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData pie_chart = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData piggy_bank = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData placeholder = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData printer = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData reload = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData settings_1 = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData shopping_bag = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData shopping_cart = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData shuffle = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData speaker = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData musical_note = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData upload_1 = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData vector = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData next_1 = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData tag = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData upload = const IconData(0xe833, fontFamily: _kFontFam);
}
